### ISSUE TITLE
Update action to do pipy deployment 

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/navigator-lib#17]

**Comment by RaulTrombin** [comment]
It's on progress on [Pypi-PR](https://github.com/bluerobotics/navigator-lib/pull/15)
draft pypi module can be tested on : [navigator-pypi](https://pypi.org/project/br-navigator/)
`pip install br_navigator`

**Comment by patrickelectric** [comment]
is there a reason for be a draft ?

**Comment by RaulTrombin** [comment]
actually not, it will be triggered only on tags,
but the module name and version should be carefully set up beforece any official release,
it's better to validade the core-lib a bit more and test with br_navigator.

**Comment by RaulTrombin** [comment]
We can close this since we are using pypi-publish action with thrusted publishers.
