### ISSUE TITLE
create python release

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/navigator-lib#23]

**Comment by RaulTrombin** [comment]
Needs

- [ ] https://github.com/bluerobotics/navigator-lib/pull/34
- [ ] https://github.com/bluerobotics/navigator-lib/pull/32

**Comment by RaulTrombin** [comment]
ping @patrickelectric

**Comment by RaulTrombin** [comment]
Just finishing some adjustments on python documentation PR.
The 2 above are pending.
