### ISSUE TITLE
Trying to initialize gives permission denied error

### ISSUE THREAD

**Issue by democat3457** [bluerobotics/navigator-lib#50]
After installing the navigator pip package, I am unable to initialize the navigator module:
```
pi@blueos:~ $ python
Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bluerobotics_navigator as navigator
>>> navigator.init()
thread '<unnamed>' panicked at 'Error: Setting CS2 pin as output: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/navigator-rs-0.2.1/src/lib.rs:316:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyo3_runtime.PanicException: Error: Setting CS2 pin as output: Io(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })
>>>
```
How do I fix this?

**Comment by patrickelectric** [comment]
Hi Colin,

Depending of the OS and user that will happen.

Try running python with root user or sudo

My best regards,

**Comment by democat3457** [comment]
It works with sudo, but is there any way to do it with the normal user? Running with sudo every time feels a little unsafe.

**Comment by RaulTrombin** [comment]
@democat3457 which linux kernel are you using?

```
`blueos@raspberrypi-armv7:~/github/navigator-rs $ uname -a
Linux raspberrypi-armv7 5.10.33-v7l+ #1415 SMP Fri Apr 30 15:50:57 BST 2021 armv7l GNU/Linux`
```

**Comment by joaoantoniocardoso** [comment]
> It works with sudo, but is there any way to do it with the normal user? Running with sudo every time feels a little unsafe.

There is, your user needs to be part of a group with such permissions. The specific group depends on the distro and sometimes needs to be manually added, as shown in [this](https://forum.up-community.org/discussion/2141/solved-tutorial-gpio-i2c-spi-access-without-root-permissions) post.
