### ISSUE TITLE
README: warn about using together with autopilot firmware

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/navigator-lib#57]
Issues like [this](https://discuss.bluerobotics.com/t/panic-while-running-bluerobotics-navigator-resource-busy/15504/3) could likely be avoided (or at least reduced) if the README mentioned that it's for direct control, and that it doesn't play nicely with other software trying to talk to the peripherals at the same time. It would likely also be helpful to mention MAVLink communication as a higher level interface for people who just want to talk to the autopilot.

**Comment by RaulTrombin** [comment]
@ES-Alexander  Can you check https://github.com/bluerobotics/navigator-lib/pull/67 ?
