### ISSUE TITLE
navigator.init() crashes

### ISSUE THREAD

**Issue by DRL** [bluerobotics/navigator-lib#58]
Hi,

I have bluerobotics-navigator 0.0.2 installed on the following Rpi

> Linux rpi 5.10.33-v8+ #1415 SMP PREEMPT Fri Apr 30 15:53:26 BST 2021 aarch64 GNU/Linux

but run into this error when running `bluerobotics_navigator.init()`
```
~ $ python
Python 3.9.2 (default, Mar 12 2021, 04:06:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bluerobotics_navigator as navigator
>>> navigator.init()
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/navigator-rs-0.3.0/src/lib.rs:278:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

any ideas what we can do to make it work?

The navigator board works and the navigator library work fine in the webapp terminal of BlueOS 1.1.1 ...

cheers, 

dom

**Comment by RaulTrombin** [comment]
Hi @DRL,

I've updated the README with the instructions provided by email to set up the overlays. 
Can we confirm that the scripts fixed those issues?

We are working to deploy the newer version with PWM relay mode and a leak sensor.

**Comment by DRL** [comment]
Hi @RaulTrombin,

yes, I can confirm that these instructions solve the issue.

Thank you,

dom
