### ISSUE TITLE
pip install bluerobotics_navigator not working

### ISSUE THREAD

**Issue by edxmorgan** [bluerobotics/navigator-lib#79]
![Screenshot from 2024-11-25 16-14-27](https://github.com/user-attachments/assets/730e9202-35aa-44e3-bdb0-2ee6a457f7e0)

**Comment by RaulTrombin** [comment]
Hello @edxmorgan, which architecture are you using?

Can you send your uname -a output?

Currently Navigator is developed and tested on armv7 and aarch64 targets for Raspberry Pi with Raspbian/BlueOS.
Can you provide more details about your setup and how you integrated Navigator?

**Comment by edxmorgan** [comment]
Hello @RaulTrombin ,

uname -a output is **Linux p330 6.8.0-49-generic #49~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov  6 17:42:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux**

Does this mean navigator can not be used as api to control the bluerov from an x86_64 machine ?

**Comment by RaulTrombin** [comment]
Navigator Python, C, and Rust libraries interface with the hardware directly, it communicate directly with sensors over I2C/SPI buses.

If you have BlueOS running on your ROV, you can install the Jupyter extension and code directly through the web (the Python code will run on the Raspberry Pi).

Another option is to use [navigator-web-assistant](https://discuss.bluerobotics.com/t/navigator-webassistant/16029), 
which binds all these features to web technologies such as REST API and WebSocket.
This allows you to either write Python code locally to interface over WebSocket (there's an example inside the Jupyter extension), or develop a web app with javascript, 
or even use our Node-RED extension, which allows you to create flow graphs very quickly and easily.

**Comment by edxmorgan** [comment]
@RaulTrombin thank you for the explanation . I explore these options.
